生活条件:
  - 学校允许点外卖吗，取外卖的地方离宿舍楼多远
  - 学校交通便利吗，有地铁吗，在市区吗，不在的话进城要多久
  - 学校的超市怎么样
  - 自由补充
有无空调:
  - 教室和宿舍有没有空调
宿舍几人间:
  - 宿舍是上床下桌
有无独立卫浴:
  - 有独立卫浴吗
有无早晚自习:
  - 早自习
  - 晚自习
有无早操:
  - 有晨跑
  - 跑步打卡
宵禁情况:
  - 门禁
  - 查寝
  - 封寝
  - 晚归
到点是否断电断网:
  - 断电断网
  - 宿舍限电
