slug_overrides:
  青岛大学: [qing-dao-da-xue]
  山东师范大学: [shan-dong-shi-fan-da-xue]
  曲阜师范大学: [qu-fu-shi-fan-da-xue]
  济南大学: [ji-nan-da-xue, shan-dong-ji-nan-da-xue]
  山东科技大学: [shan-dong-ke-ji-da-xue]
  烟台大学: [yan-tai-da-xue]
  山东政法学院: [shan-dong-zheng-fa-xue-yuan]
  山东财经大学: [shan-dong-cai-jing-da-xue]
  临沂大学: [lin-yi-da-xue]
  聊城大学: [liao-cheng-da-xue]
  青岛农业大学: [qing-dao-nong-ye-da-xue]
  鲁东大学: [lu-dong-da-xue]
  山东工商学院: [shan-dong-gong-shang-xue-yuan]
  潍坊学院: [wei-fang-xue-yuan]
  齐鲁师范学院: [qi-lu-shi-fan-xue-yuan]
  山东管理学院: [shan-dong-guan-li-xue-yuan]
  山东农业工程学院: [shan-dong-nong-ye-gong-cheng-xue-yuan]
  山东青年政治学院: [shan-dong-qing-nian-zheng-zhi-xue-yuan]
  济宁学院: [ji-zhu-xue-yuan, ji-ning-xue-yuan]
  泰山学院: [tai-shan-xue-yuan]
  枣庄学院: [zao-zhuang-xue-yuan]
  菏泽学院: [he-ze-xue-yuan]
  德州学院: [de-zhou-xue-yuan]
  山东航空学院（原滨州学院）: [shan-dong-hang-kong-xue-yuan, bin-zhou-xue-yuan]

aliases:
  山东航空学院（原滨州学院）: [山东航空学院, 滨州学院]
